/* glossary-matches.js — surface forms that the DP glossary auto-linker may
   turn into definition links. Hand-maintained; edit freely.

   glossary-data.js is generated from the IB definitions spreadsheet and holds
   the official term and its verbatim definition. This file holds everything
   ELSE a term might look like in running text: plurals, verb forms,
   adjectives, US spellings, abbreviations, and the informal names a page is
   more likely to use ("abrasive" for Abrading, "3D printed" for 3D Printing).

   Keys are term ids from glossary-data.js. A term missing from this file is
   never auto-linked (it can still be tagged by hand with <span class="gloss">).

   Per term:
     match  forms that link on every DP page. Matched case-insensitively on
            whole words. A space or hyphen in a form matches either a space
            or a hyphen on the page, so "belt-driven" also matches
            "belt driven". Straight and curly apostrophes are interchangeable.
     local  forms that only link on the term's own topic pages and their A/B
            sibling (A3.4 and B3.4 count as one family). For words that mean
            something else elsewhere: "stress" on a structures page is the
            glossary term, on C1.3 it is not.
     exact  forms matched case-sensitively, for abbreviations. "LED" links,
            "led" does not.
     also   extra topic codes where the local forms may link.

   When two terms could claim the same words, the longer match wins on the
   page, and every form must belong to exactly one term. Run
   check-matches.py after editing to catch collisions, unknown ids, and forms
   that never occur in the topic pages.

   Not auto-linked on purpose (the IB "definition" is a list, a formula, or a
   cross-reference, or the word is too generic): Advantage of UCD,
   Disadvantages of UCD, Five Stages of UCD, Current/Resistance/Voltage,
   Levers (Mechanical Advantage), Research Methodologies, Form.
*/
window.DP_GLOSSARY_MATCHES = {
  "1st-class-lever": {"match": ["1st-class lever", "1st-class levers", "first-class lever", "first-class levers", "class 1 lever", "class 1 levers", "class one lever", "class one levers"]},
  "2nd-class-lever": {"match": ["2nd-class lever", "2nd-class levers", "second-class lever", "second-class levers", "class 2 lever", "class 2 levers", "class two lever", "class two levers"]},
  "3d-printing": {"match": ["3d printing", "3d printed", "3d print", "3d prints", "3d printer", "3d printers"]},
  "3rd-class-lever": {"match": ["3rd-class lever", "3rd-class levers", "third-class lever", "third-class levers", "class 3 lever", "class 3 levers", "class three lever", "class three levers"]},
  "4d-printing": {"match": ["4d printing", "4d printed", "4d print", "4d prints"]},
  "5d-printing": {"match": ["5d printing", "5d printed", "5d print", "5d prints"]},
  "abrading": {"match": ["abrading", "abrade", "abrades", "abraded", "abrasion", "abrasions", "abrasive", "abrasives"]},
  "active-electronic-components": {"match": ["active electronic component", "active electronic components", "active component", "active components"]},
  "additive-manufacturing": {"match": ["additive manufacturing", "additive manufacture", "additively manufactured"]},
  "adhering": {"match": ["adhering", "adhere", "adheres", "adhered", "adhesive", "adhesives", "adhesion", "adhesive bonding"]},
  "adjustability": {"match": ["adjustability", "adjustable"]},
  "aesthetic-characteristics": {"match": ["aesthetic characteristics", "aesthetic characteristic"]},
  "aesthetic-prototype": {"match": ["aesthetic prototype", "aesthetic prototypes", "aesthetic prototyping"]},
  "ampere": {"match": ["ampere", "amperes", "amps", "amperage"]},
  "analogue-system-electronics": {"match": ["analogue system", "analogue systems", "analog system", "analog systems", "analogue electronics", "analog electronics", "analogue signal", "analogue signals", "analog signal", "analog signals"], "local": ["analogue", "analog"]},
  "and-gate": {"exact": ["AND gate", "AND gates"]},
  "anodizing": {"match": ["anodizing", "anodising", "anodized", "anodised", "anodize", "anodise"]},
  "anthropometrics": {"match": ["anthropometrics", "anthropometric", "anthropometry", "anthropometrical"]},
  "assembled-drawings": {"match": ["assembled drawing", "assembled drawings", "assembly drawing", "assembly drawings"]},
  "assembly-line-production": {"match": ["assembly-line production", "assembly line", "assembly lines"]},
  "attract-converse-transact-model-act": {"match": ["attract/converse/transact", "attract, converse, transact", "attract-converse-transact", "act model", "act framework"], "exact": ["ACT"]},
  "augmented-reality-ar": {"match": ["augmented reality"], "exact": ["AR"]},
  "automated-production": {"match": ["automated production"]},
  "batch-production": {"match": ["batch production", "batch produced"], "local": ["batch", "batches"]},
  "bell-crank-linkage": {"match": ["bell crank linkage", "bell crank linkages", "bell crank", "bell cranks"]},
  "belt-driven-system": {"match": ["belt-driven system", "belt-driven systems", "belt drive", "belt drives", "belt-driven"]},
  "bending-force": {"match": ["bending force", "bending forces", "bending moment", "bending moments"], "local": ["bending"]},
  "bevel-gear": {"match": ["bevel gear", "bevel gears"]},
  "binary-digit": {"match": ["binary digit", "binary digits"], "local": ["binary"]},
  "bio-materials": {"match": ["bio-material", "bio-materials", "biomaterial", "biomaterials", "bio-based material", "bio-based materials"]},
  "biodegradable-material": {"match": ["biodegradable material", "biodegradable materials", "biodegradable polymer", "biodegradable polymers", "biodegradable", "biodegradability", "biodegrade", "biodegrades", "biodegradation"]},
  "biomechanics": {"match": ["biomechanics", "biomechanical", "biomechanic"]},
  "bluetooth": {"match": ["bluetooth"]},
  "boolean-algebra": {"match": ["boolean algebra", "boolean logic", "boolean"]},
  "built-environment": {"match": ["built environment", "built environments"]},
  "buzzer": {"match": ["buzzer", "buzzers"]},
  "cam": {"match": ["cam follower", "cam followers", "cam and follower", "camshaft", "camshafts"], "local": ["cam", "cams"]},
  "cantilever-beam": {"match": ["cantilever beam", "cantilever beams", "cantilever", "cantilevers", "cantilevered"]},
  "capacitor": {"match": ["capacitor", "capacitors", "capacitance"]},
  "casting": {"match": ["casting", "castings", "sand casting", "investment casting"]},
  "chemical-properties": {"match": ["chemical properties", "chemical property"]},
  "circular-economy": {"match": ["circular economy", "circular economies", "circular economic model", "circularity"]},
  "clearance": {"match": ["clearance", "clearances"]},
  "closed-loop-system": {"match": ["closed-loop system", "closed-loop systems", "closed-loop control", "closed loop"]},
  "column": {"local": ["column", "columns"]},
  "composite-material": {"match": ["composite material", "composite materials"], "local": ["composite", "composites"], "also": ["A3.2", "B3.2", "A4.1", "B4.1"]},
  "compound-gear": {"match": ["compound gear", "compound gears", "compound gear train", "compound gear trains"]},
  "compression-force": {"match": ["compression", "compressive force", "compressive forces", "compressive load", "compressive loads"]},
  "compressive-strength": {"match": ["compressive strength"]},
  "computer-aided-design-cad": {"match": ["computer-aided design"], "exact": ["CAD"]},
  "computer-integrated-manufacturing-cim": {"match": ["computer integrated manufacturing", "computer integrated manufacture"], "exact": ["CIM"]},
  "constructive-discontent": {"match": ["constructive discontent"]},
  "continuous-production": {"match": ["continuous production", "continuous flow production"]},
  "continuously-supported-beam": {"match": ["continuously supported beam", "continuously supported beams"]},
  "control-circuit": {"match": ["control circuit", "control circuits", "control circuitry"]},
  "corrosion-resistance": {"match": ["corrosion resistance", "corrosion resistant", "resistance to corrosion", "corrosion"]},
  "cradle-to-cradle": {"match": ["cradle-to-cradle"], "exact": ["C2C"]},
  "cradle-to-grave": {"match": ["cradle-to-grave"]},
  "craft-production": {"match": ["craft production", "craft produced", "craft-based production"]},
  "current": {"match": ["electric current", "electrical current"], "local": ["current", "currents"]},
  "datschefskis-five-principles-of-sustainable-design": {"match": ["datschefski's five principles", "datschefski's principles", "five principles of sustainable design", "datschefski", "datschefski's"]},
  "dematerialization": {"match": ["dematerialization", "dematerialisation", "dematerialize", "dematerialise", "dematerialized", "dematerialised"]},
  "density": {"match": ["density", "densities"]},
  "design-for-assembly": {"match": ["design for assembly"], "exact": ["DfA", "DFA"]},
  "design-for-disassembly": {"match": ["design for disassembly"], "exact": ["DfD", "DFD"]},
  "design-for-extremes": {"match": ["design for extremes", "designing for extremes"]},
  "design-for-manufacture-dfm": {"match": ["design for manufacture", "design for manufacturing"], "exact": ["DfM", "DFM"]},
  "design-for-process": {"match": ["design for process", "design for the process"]},
  "design-specification": {"match": ["design specification", "design specifications", "design spec", "design specs"]},
  "design-thinking": {"match": ["design thinking"]},
  "designing-a-solution-stage": {"match": ["designing a solution stage", "designing a solution"]},
  "die-casting": {"match": ["die casting", "die castings", "die cast"]},
  "digital-human": {"match": ["digital human", "digital humans", "digital human modelling"]},
  "digital-system-electronics": {"match": ["digital system", "digital systems", "digital electronics", "digital signal", "digital signals"], "local": ["digital"]},
  "diode": {"match": ["diode", "diodes"]},
  "drawings-2d-3d-assembled-isometric-orthographic-projection": {"match": ["2d drawing", "2d drawings", "3d drawing", "3d drawings", "technical drawing", "technical drawings", "working drawing", "working drawings"]},
  "ductility": {"match": ["ductility", "ductile"]},
  "dynamic-data": {"match": ["dynamic data", "dynamic anthropometric data"]},
  "dynamic-force": {"match": ["dynamic force", "dynamic forces", "dynamic load", "dynamic loads", "dynamic loading"]},
  "efficiency-usability": {"local": ["efficiency"]},
  "elasticity": {"match": ["elasticity", "elastic deformation", "elastic limit"], "local": ["elastic"], "also": ["A3.2", "B3.2"]},
  "electrical-resistivity-electrical-conductivity": {"match": ["electrical resistivity", "electrical conductivity", "resistivity", "electrically conductive", "electrically insulating"]},
  "electro-rheostatic": {"match": ["electro-rheostatic", "electrorheostatic", "electro-rheological", "electrorheological"]},
  "electronic-circuit": {"match": ["electronic circuit", "electronic circuits"], "local": ["circuit", "circuits"]},
  "electronic-system": {"match": ["electronic system", "electronic systems"]},
  "electroplating": {"match": ["electroplating", "electroplated", "electroplate"]},
  "embedded-system": {"match": ["embedded system", "embedded systems"]},
  "empathize-stage": {"match": ["empathize stage", "empathise stage"], "local": ["empathize", "empathise"]},
  "environment": {"local": ["environment", "environments"]},
  "equilibrium-force": {"match": ["equilibrium", "static equilibrium"]},
  "ergonomics": {"match": ["ergonomics", "ergonomic", "ergonomically", "ergonomist", "ergonomists"]},
  "errors-usability": {"match": ["user error", "user errors", "error rate", "error rates"], "local": ["error", "errors"]},
  "exploded-drawing": {"match": ["exploded drawing", "exploded drawings", "exploded view", "exploded views", "exploded diagram", "exploded diagrams"]},
  "fastening": {"match": ["fastening", "fastenings", "fastener", "fasteners", "fasten", "fastened", "mechanical fastening", "mechanical fasteners"]},
  "feedback-loop": {"match": ["feedback loop", "feedback loops"]},
  "field-research": {"match": ["field research", "field study", "field studies"]},
  "finishing-techniques": {"match": ["finishing techniques", "finishing technique", "surface finishing", "surface finish", "surface finishes", "finishing process", "finishing processes"]},
  "finite-element-analysis-fea": {"match": ["finite element analysis"], "exact": ["FEA"]},
  "fixed-beam": {"match": ["fixed beam", "fixed beams", "fixed-end beam", "fixed-end beams"]},
  "fixed-resistor": {"match": ["fixed resistor", "fixed resistors"]},
  "flammability": {"match": ["flammability", "flammable", "non-flammable", "flame resistant"]},
  "flow-diagram": {"match": ["flow diagram", "flow diagrams", "flowchart", "flowcharts", "flow chart", "flow charts"]},
  "focus-group": {"match": ["focus group", "focus groups"]},
  "forces": {"local": ["force", "forces"]},
  "forming-techniques": {"match": ["forming techniques", "forming technique", "forming process", "forming processes"], "local": ["forming"]},
  "four-pleasure-framework": {"match": ["four-pleasure framework", "four-pleasures framework", "four pleasures", "four-pleasure model"]},
  "fracture-point": {"match": ["fracture point", "fracture points", "point of fracture"], "local": ["fracture"], "also": ["A3.1", "B3.1"]},
  "frame-structure": {"match": ["frame structure", "frame structures", "framed structure", "framed structures"]},
  "free-hand-sketching": {"match": ["free-hand sketching", "free-hand sketch", "free-hand sketches", "freehand sketching", "freehand sketch", "freehand sketches", "freehand drawing", "freehand drawings"]},
  "frequency": {"local": ["frequency", "frequencies"]},
  "fulcrum-lever": {"match": ["fulcrum", "fulcrums"]},
  "functional-obsolescence": {"match": ["functional obsolescence", "functionally obsolete"]},
  "functional-prototype": {"match": ["functional prototype", "functional prototypes", "functional prototyping", "working prototype", "working prototypes"]},
  "fused-deposition-modelling-fdm": {"match": ["fused deposition modelling", "fused deposition modeling", "fused filament fabrication"], "exact": ["FDM", "FFF"]},
  "galvanizing": {"match": ["galvanizing", "galvanising", "galvanized", "galvanised", "galvanize", "galvanise", "galvanization", "galvanisation"]},
  "gear-driven-system": {"match": ["gear-driven system", "gear-driven systems", "gear drive", "gear drives", "gear-driven", "gear train", "gear trains", "gearbox", "gearboxes"]},
  "gears": {"match": ["gear", "gears", "gear ratio", "gear ratios", "gearing"]},
  "generative-design": {"match": ["generative design"]},
  "glass": {"local": ["glass"]},
  "haptic-technology": {"match": ["haptic technology", "haptic technologies", "haptics", "haptic feedback", "haptic"]},
  "hardness": {"match": ["hardness"]},
  "hertz-hz": {"match": ["hertz"], "exact": ["Hz"]},
  "high-fidelity-prototype": {"match": ["high-fidelity prototype", "high-fidelity prototypes", "high-fidelity prototyping", "high-fidelity", "hi-fi prototype", "hi-fi prototypes"]},
  "hybrid-production-system": {"match": ["hybrid production system", "hybrid production systems", "hybrid production"]},
  "hygroscopy": {"match": ["hygroscopy", "hygroscopic", "hygroscopicity"]},
  "ideation-techniques": {"match": ["ideation techniques", "ideation technique", "ideation"]},
  "ideo-pleasure": {"match": ["ideo-pleasure", "ideo-pleasures"]},
  "idler-gear": {"match": ["idler gear", "idler gears", "idler"]},
  "inclusive-design-universal-design": {"match": ["inclusive design", "universal design", "inclusively designed"]},
  "injection-moulding": {"match": ["injection moulding", "injection molding", "injection moulded", "injection molded", "injection mould", "injection moulds", "injection mold", "injection molds"]},
  "input-devices": {"match": ["input device", "input devices"]},
  "integrated-circuit": {"match": ["integrated circuit", "integrated circuits"], "exact": ["IC", "ICs"]},
  "internet-of-things-iot": {"match": ["internet of things"], "exact": ["IoT", "IOT"]},
  "interview": {"match": ["interview", "interviews", "interviewing"]},
  "isometric-drawing": {"match": ["isometric drawing", "isometric drawings", "isometric projection", "isometric view", "isometric views", "isometric"]},
  "iterative-design": {"match": ["iterative design", "iterative", "iteration", "iterations", "iterate", "iterating"]},
  "joining-techniques": {"match": ["joining techniques", "joining technique", "joining process", "joining processes", "joining method", "joining methods"], "local": ["joining"]},
  "laminated-object-manufacture-lom": {"match": ["laminated object manufacture", "laminated object manufacturing"], "exact": ["LOM"]},
  "lamination": {"match": ["lamination", "laminating", "laminated", "laminate", "laminates"]},
  "learnability-usability": {"local": ["learnability"]},
  "lever": {"match": ["lever", "levers"]},
  "levers-effort": {"match": ["effort arm", "effort force"], "local": ["effort"]},
  "levers-load": {"match": ["load arm", "resistance arm"]},
  "life-cycle-analysis": {"match": ["life-cycle analysis", "life-cycle assessment", "lifecycle analysis", "lifecycle assessment"], "exact": ["LCA", "LCAs"]},
  "light-emitting-diode-led": {"match": ["light-emitting diode", "light-emitting diodes"], "exact": ["LED", "LEDs"]},
  "linear-approach-economy": {"match": ["linear economy", "linear economies", "linear approach", "take-make-dispose"]},
  "linear-motion": {"match": ["linear motion"]},
  "linkage": {"match": ["linkage", "linkages"]},
  "liquid-crystal-display-lcd": {"match": ["liquid crystal display", "liquid crystal displays"], "exact": ["LCD", "LCDs"]},
  "literature-search": {"match": ["literature search", "literature searches", "literature review", "literature reviews"]},
  "load": {"local": ["load", "loads", "loading"], "also": ["A3.2", "B3.2"]},
  "logic-gate": {"match": ["logic gate", "logic gates"]},
  "low-fidelity-prototype": {"match": ["low-fidelity prototype", "low-fidelity prototypes", "low-fidelity prototyping", "low-fidelity", "lo-fi prototype", "lo-fi prototypes"]},
  "machine-manufacturing": {"match": ["machining", "machined", "machine tool", "machine tools"], "local": ["machine", "machines"]},
  "magneto-rheostatic": {"match": ["magneto-rheostatic", "magnetorheostatic", "magneto-rheological", "magnetorheological"]},
  "malleability": {"match": ["malleability", "malleable"]},
  "manufactured-material": {"match": ["manufactured material", "manufactured materials", "man-made material", "man-made materials", "synthetic material", "synthetic materials"]},
  "manufacturing-techniques": {"match": ["manufacturing techniques", "manufacturing technique", "manufacturing process", "manufacturing processes", "manufacturing method", "manufacturing methods"]},
  "mass-customization": {"match": ["mass customization", "mass customisation", "mass customized", "mass customised"]},
  "mass-production": {"match": ["mass production", "mass produced", "mass producing"]},
  "material-extrusion": {"match": ["material extrusion"]},
  "mechanical-advantage": {"match": ["mechanical advantage"], "exact": ["MA"]},
  "mechanical-properties": {"match": ["mechanical properties", "mechanical property"]},
  "mechanical-system": {"match": ["mechanical system", "mechanical systems"]},
  "mechanized-production": {"match": ["mechanized production", "mechanised production", "mechanized", "mechanised", "mechanization", "mechanisation"]},
  "melting-point": {"match": ["melting point", "melting points", "melting temperature"]},
  "memorability-usability": {"local": ["memorability"]},
  "microcontroller": {"match": ["microcontroller", "microcontrollers", "micro-controller", "micro-controllers"]},
  "mock-up": {"match": ["mock-up", "mock-ups", "mockup", "mockups", "mocked up"]},
  "model-test-refine-cycle": {"match": ["model-test-refine cycle", "model-test-refine", "model, test, refine cycle", "model, test, refine", "model, test and refine"]},
  "motion-capture": {"match": ["motion capture", "mocap"]},
  "motor-electronics": {"match": ["electric motor", "electric motors", "dc motor", "dc motors", "servo motor", "servo motors", "stepper motor", "stepper motors"], "local": ["motor", "motors"], "also": ["A3.3", "B3.3"]},
  "moulding": {"match": ["moulding", "molding", "moulded", "molded", "mould", "moulds", "mold", "molds", "blow moulding", "rotational moulding", "compression moulding", "vacuum moulding"]},
  "multimeter": {"match": ["multimeter", "multimeters"]},
  "natural-materials": {"match": ["natural material", "natural materials"]},
  "not-gate": {"exact": ["NOT gate", "NOT gates"]},
  "ohm": {"match": ["ohm", "ohms", "ohm's law"]},
  "one-off-production": {"match": ["one-off production"], "local": ["one-off", "one-offs"]},
  "open-loop-system": {"match": ["open-loop system", "open-loop systems", "open-loop control", "open loop"]},
  "operational-amplifier-op-amp": {"match": ["operational amplifier", "operational amplifiers", "op-amp", "op-amps"]},
  "or-gate": {"exact": ["OR gate", "OR gates"]},
  "orthographic-projection": {"match": ["orthographic projection", "orthographic projections", "orthographic drawing", "orthographic drawings", "orthographic"]},
  "oscillating-motion": {"match": ["oscillating motion", "oscillation", "oscillations", "oscillating", "oscillate", "oscillates"]},
  "oscilloscope": {"match": ["oscilloscope", "oscilloscopes"]},
  "output": {"match": ["output device", "output devices"], "local": ["output", "outputs"]},
  "parallel-circuit": {"match": ["parallel circuit", "parallel circuits"], "local": ["in parallel"]},
  "parallel-linkage": {"match": ["parallel linkage", "parallel linkages", "parallel motion linkage", "parallelogram linkage"]},
  "passive-electronic-components": {"match": ["passive electronic component", "passive electronic components", "passive component", "passive components"]},
  "percentile": {"match": ["percentile", "percentiles", "5th percentile", "50th percentile", "95th percentile"]},
  "percentile-range-upper-and-lower-limits": {"match": ["percentile range", "percentile ranges", "5th to 95th percentile", "5th-95th percentile"]},
  "photochromicity": {"match": ["photochromicity", "photochromic", "photochromism"]},
  "physical-properties": {"match": ["physical properties", "physical property"]},
  "physical-prototype": {"match": ["physical prototype", "physical prototypes", "physical prototyping", "physical model", "physical models"]},
  "physio-pleasure": {"match": ["physio-pleasure", "physio-pleasures"]},
  "physiology-factors": {"match": ["physiology factors", "physiological factors", "physiological factor", "physiology"]},
  "piezoelectricity": {"match": ["piezoelectricity", "piezoelectric", "piezo-electric", "piezo"]},
  "planned-obsolescence": {"match": ["planned obsolescence"]},
  "plasticity": {"match": ["plasticity", "plastic deformation", "plastic region", "plastically"]},
  "polishing": {"match": ["polishing"], "local": ["polished", "polish"]},
  "polymer": {"match": ["polymer", "polymers", "polymeric", "thermoplastic", "thermoplastics", "thermoset", "thermosets", "thermosetting"]},
  "population-stereotype": {"match": ["population stereotype", "population stereotypes"]},
  "powder-bed-fusion-pbf": {"match": ["powder bed fusion"], "exact": ["PBF"]},
  "power": {"match": ["electrical power", "electric power"], "local": ["power"]},
  "press-forming": {"match": ["press forming", "press formed", "press form"]},
  "primary-persona": {"match": ["primary persona", "primary personas", "persona", "personas"]},
  "problem-statement": {"match": ["problem statement", "problem statements"]},
  "processing-devices": {"match": ["processing device", "processing devices", "processor", "processors"]},
  "product-analysis": {"match": ["product analysis", "product analyses"]},
  "product-requirements": {"match": ["product requirement", "product requirements"]},
  "production-system": {"match": ["production system", "production systems"]},
  "programmable-integrated-circuit-pic": {"match": ["programmable integrated circuit", "programmable integrated circuits", "programmable interface controller"], "exact": ["PIC", "PICs"]},
  "prototype": {"match": ["prototype", "prototypes", "prototyping", "prototyped"]},
  "prototyping-techniques": {"match": ["prototyping techniques", "prototyping technique", "prototyping methods", "prototyping method"]},
  "psycho-pleasure": {"match": ["psycho-pleasure", "psycho-pleasures"]},
  "psychology-factors": {"match": ["psychology factors", "psychological factors", "psychological factor"]},
  "pulley": {"match": ["pulley", "pulleys", "pulley system", "pulley systems", "block and tackle"]},
  "qualitative-data": {"match": ["qualitative data", "qualitative", "qualitative research"]},
  "quantitative-data": {"match": ["quantitative data", "quantitative", "quantitative research"]},
  "rack-and-pinion": {"match": ["rack and pinion", "rack & pinion"]},
  "range-of-sizes": {"match": ["range of sizes", "size range", "size ranges"]},
  "rapid-prototyping": {"match": ["rapid prototyping", "rapid prototype", "rapid prototypes", "rapidly prototyped"]},
  "ratchet-and-pawl": {"match": ["ratchet and pawl", "ratchet", "ratchets", "pawl", "pawls"]},
  "reach": {"match": ["reach envelope", "reach zone", "reach zones", "reach range"], "local": ["reach"]},
  "reactivity-food-safe": {"match": ["reactivity", "chemical reactivity", "food safe"]},
  "reciprocating-motion": {"match": ["reciprocating motion", "reciprocating", "reciprocation", "reciprocate", "reciprocates"]},
  "relay": {"local": ["relay", "relays"]},
  "renewable-energy-sources": {"match": ["renewable energy source", "renewable energy sources", "renewable energy", "renewables", "renewable resource", "renewable resources"]},
  "research-question": {"match": ["research question", "research questions"]},
  "research-stage": {"match": ["research stage"]},
  "resistance": {"match": ["electrical resistance"], "local": ["resistance"]},
  "reverse-engineering": {"match": ["reverse engineering", "reverse engineer", "reverse engineered"]},
  "reverse-linkage": {"match": ["reverse linkage", "reverse linkages", "reverse motion linkage"]},
  "rotary-motion": {"match": ["rotary motion", "rotational motion", "rotary"]},
  "safety-factor-sf": {"match": ["safety factor", "safety factors", "factor of safety", "factors of safety"], "exact": ["SF", "SFs"]},
  "satisfaction-usability": {"match": ["user satisfaction"], "local": ["satisfaction"]},
  "scale-of-production": {"match": ["scale of production", "scales of production", "production scale", "production scales"]},
  "scale-prototype": {"match": ["scale prototype", "scale prototypes", "scale model", "scale models", "scaled model", "scaled models", "scaled prototype"]},
  "scenario": {"local": ["scenario", "scenarios"]},
  "secondary-research": {"match": ["secondary research", "secondary source", "secondary sources", "secondary data"]},
  "selective-laser-sintering-sls": {"match": ["selective laser sintering", "laser sintering"], "exact": ["SLS"]},
  "sensor": {"match": ["sensor", "sensors"]},
  "series-circuit": {"match": ["series circuit", "series circuits"], "local": ["in series"]},
  "shape-memory-material": {"match": ["shape memory material", "shape memory materials", "shape memory alloy", "shape memory alloys", "shape memory polymer", "shape memory polymers", "shape memory"], "exact": ["SMA", "SMAs"]},
  "shear-force": {"match": ["shear force", "shear forces", "shear", "shearing"]},
  "shell-structure": {"match": ["shell structure", "shell structures", "monocoque"]},
  "signal-conditioning": {"match": ["signal conditioning", "signal conditioner", "signal conditioners", "conditioned signal"]},
  "simply-supported-beams": {"match": ["simply supported beam", "simply supported beams"]},
  "smart-materials": {"match": ["smart material", "smart materials"]},
  "social-obsolescence": {"match": ["social obsolescence", "socially obsolete"]},
  "socio-pleasure": {"match": ["socio-pleasure", "socio-pleasures"]},
  "solid-model": {"match": ["solid model", "solid models", "solid modelling", "solid modeling"]},
  "solid-structure": {"match": ["solid structure", "solid structures", "mass structure", "mass structures"]},
  "spur-gear": {"match": ["spur gear", "spur gears"]},
  "static-data": {"match": ["static data", "static anthropometric data", "structural data"]},
  "static-force": {"match": ["static force", "static forces", "static load", "static loads", "static loading"]},
  "stereolithography-sla": {"match": ["stereolithography", "stereo-lithography"], "exact": ["SLA"]},
  "stiffness": {"match": ["stiffness", "stiff", "stiffer", "stiffest"]},
  "stitching": {"match": ["stitching", "stitched", "stitch", "stitches"]},
  "storyboard": {"match": ["storyboard", "storyboards", "storyboarding"]},
  "strain": {"local": ["strain", "strains"], "also": ["A3.1", "B3.1"]},
  "stress": {"local": ["stress", "stresses"], "also": ["A3.1", "B3.1"]},
  "stress-strain-graph": {"match": ["stress-strain graph", "stress-strain graphs", "stress-strain curve", "stress-strain curves", "stress-strain diagram", "stress/strain graph", "stress/strain curve"]},
  "structural-system": {"match": ["structural system", "structural systems"]},
  "strut": {"match": ["strut", "struts"]},
  "style-obsolescence": {"match": ["style obsolescence", "stylistic obsolescence", "aesthetic obsolescence", "stylistically obsolete"]},
  "subtractive-manufacturing": {"match": ["subtractive manufacturing", "subtractive manufacture", "subtractive process", "subtractive processes", "subtractive"]},
  "surface-model": {"match": ["surface model", "surface models", "surface modelling", "surface modeling"]},
  "sustainability": {"match": ["sustainability", "sustainable", "sustainably", "unsustainable"]},
  "switch-electronics": {"local": ["switch", "switches"]},
  "swot-analysis": {"match": ["swot analysis", "swot analyses"], "exact": ["SWOT"]},
  "take-back-legislation": {"match": ["take-back legislation", "take-back scheme", "take-back schemes", "take-back program", "take-back programs", "take-back programme", "take-back programmes", "take-back"]},
  "target-user": {"match": ["target user", "target users", "target user group", "target audience"]},
  "task": {"local": ["task", "tasks"]},
  "task-analysis": {"match": ["task analysis", "task analyses"]},
  "technological-obsolescence": {"match": ["technological obsolescence", "technology obsolescence", "technologically obsolete"]},
  "tensile-strength": {"match": ["tensile strength"]},
  "tension-force": {"match": ["tensile force", "tensile forces", "tensile load", "tensile loads"], "local": ["tension"], "also": ["A3.1", "B3.1"]},
  "textiles": {"match": ["textiles", "textile", "fabric", "fabrics"]},
  "texture": {"local": ["texture", "textures", "textured"]},
  "thermal-conductivity": {"match": ["thermal conductivity", "thermal conductor", "thermal conductors", "thermal insulator", "thermal insulators", "thermally conductive"]},
  "thermal-expansion": {"match": ["thermal expansion", "coefficient of thermal expansion"]},
  "thermoelectricity": {"match": ["thermoelectricity", "thermoelectric", "thermo-electric"]},
  "timber-lumber": {"match": ["timber", "timbers", "lumber", "hardwood", "hardwoods", "softwood", "softwoods"]},
  "torsion-force": {"match": ["torsion", "torsional"]},
  "toughness": {"match": ["toughness", "toughened"]},
  "transistor": {"match": ["transistor", "transistors"]},
  "triple-bottom-line-tbl": {"match": ["triple bottom line"], "exact": ["TBL"]},
  "ubiquitous": {"match": ["ubiquitous", "ubiquity", "ubiquitously"]},
  "ultimate-strength": {"match": ["ultimate strength", "ultimate tensile strength", "ultimate tensile stress"], "exact": ["UTS"]},
  "usability": {"match": ["usability", "usable", "unusable"]},
  "usability-objectives": {"match": ["usability objective", "usability objectives", "usability goal", "usability goals"]},
  "user": {"local": ["user", "users"]},
  "user-centred-design-ucd": {"match": ["user-centred design", "user-centered design"], "exact": ["UCD"]},
  "user-centred-research-methods": {"match": ["user-centred research methods", "user-centred research method", "user-centred research", "user-centered research", "user research", "user research methods"]},
  "user-journey": {"match": ["user journey", "user journeys", "user's journey", "journey map", "journey mapping"]},
  "user-observation": {"match": ["user observation", "user observations", "observing users"]},
  "user-population": {"match": ["user population", "user populations"]},
  "user-requirements": {"match": ["user requirement", "user requirements", "user need", "user needs"]},
  "variable-resistor": {"match": ["variable resistor", "variable resistors", "potentiometer", "potentiometers", "rheostat", "rheostats"]},
  "velocity-ratios": {"match": ["velocity ratio", "velocity ratios"]},
  "virtual-prototype": {"match": ["virtual prototype", "virtual prototypes", "virtual prototyping", "digital prototype", "digital prototypes"]},
  "virtual-reality": {"match": ["virtual reality"], "exact": ["VR"]},
  "voltage": {"match": ["voltage", "voltages", "volt", "volts", "potential difference"]},
  "watt": {"match": ["watt", "watts", "wattage"]},
  "weaving": {"match": ["weaving", "woven", "weave", "weaves", "weaved"]},
  "welding": {"match": ["welding", "welded", "weld", "welds", "welder", "welders"]},
  "workspace-envelope": {"match": ["workspace envelope", "workspace envelopes", "work envelope", "work envelopes"]},
  "worm-gear": {"match": ["worm gear", "worm gears", "worm and wheel", "worm drive", "worm drives"]},
  "yield-strength": {"match": ["yield strength", "yield point", "yield points", "yield stress"]},
  "young-s-modulus": {"match": ["young's modulus", "modulus of elasticity", "elastic modulus"]}
};
