// ═══════════════════════════════════════════════════════════════════
//  You Should Play These Games — placeholder game list.
//
//  Replace each entry below with a real game. Fields:
//    slug        unique id, used for the URL anchor (#slug) — keep it
//                short, lowercase, hyphenated, and unique.
//    title       game title.
//    tagline     one-line hook shown on the cover card.
//    accent      hex color used for this game's glow, border, and
//                placeholder cover art (and its detail section's CTA).
//    platforms   array of tags shown as pills, e.g. ["PC", "Switch"].
//    why         array of 2-4 short bullets: why it's worth playing /
//                what it teaches.
//    description a couple of sentences about the game.
//    cover       optional real cover art URL. Leave unset (or null) to
//                keep the auto-generated placeholder art.
//    link        where "Where to Play" should point. "#" for now.
// ═══════════════════════════════════════════════════════════════════
const GAMES = [
  { slug: "game-01", title: "Game Title 01", tagline: "One-line hook for Game 01 — replace with the real pitch.", accent: "#FF3B69", platforms: ["PC", "Switch"], why: ["Placeholder: why this teaches problem-solving", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 01. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-02", title: "Game Title 02", tagline: "One-line hook for Game 02 — replace with the real pitch.", accent: "#FF8A3D", platforms: ["Mobile", "PC"], why: ["Placeholder: why this teaches systems thinking", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 02. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-03", title: "Game Title 03", tagline: "One-line hook for Game 03 — replace with the real pitch.", accent: "#FFD23F", platforms: ["Console", "PC"], why: ["Placeholder: why this teaches spatial reasoning", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 03. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-04", title: "Game Title 04", tagline: "One-line hook for Game 04 — replace with the real pitch.", accent: "#8BE23D", platforms: ["Switch", "Mobile"], why: ["Placeholder: why this teaches design thinking", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 04. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-05", title: "Game Title 05", tagline: "One-line hook for Game 05 — replace with the real pitch.", accent: "#2FE6A6", platforms: ["PC"], why: ["Placeholder: why this teaches logic", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 05. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-06", title: "Game Title 06", tagline: "One-line hook for Game 06 — replace with the real pitch.", accent: "#2FD8E6", platforms: ["Console", "Switch", "PC"], why: ["Placeholder: why this teaches teamwork", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 06. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-07", title: "Game Title 07", tagline: "One-line hook for Game 07 — replace with the real pitch.", accent: "#4C8CFF", platforms: ["Mobile"], why: ["Placeholder: why this teaches patience", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 07. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-08", title: "Game Title 08", tagline: "One-line hook for Game 08 — replace with the real pitch.", accent: "#7C5CFF", platforms: ["PC", "Switch"], why: ["Placeholder: why this teaches history", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 08. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-09", title: "Game Title 09", tagline: "One-line hook for Game 09 — replace with the real pitch.", accent: "#C25CFF", platforms: ["Mobile", "PC"], why: ["Placeholder: why this teaches resource management", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 09. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-10", title: "Game Title 10", tagline: "One-line hook for Game 10 — replace with the real pitch.", accent: "#FF5CAE", platforms: ["Console", "PC"], why: ["Placeholder: why this teaches storytelling", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 10. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-11", title: "Game Title 11", tagline: "One-line hook for Game 11 — replace with the real pitch.", accent: "#FF3B69", platforms: ["Switch", "Mobile"], why: ["Placeholder: why this teaches engineering", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 11. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-12", title: "Game Title 12", tagline: "One-line hook for Game 12 — replace with the real pitch.", accent: "#FF8A3D", platforms: ["PC"], why: ["Placeholder: why this teaches chemistry", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 12. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-13", title: "Game Title 13", tagline: "One-line hook for Game 13 — replace with the real pitch.", accent: "#FFD23F", platforms: ["Console", "Switch", "PC"], why: ["Placeholder: why this teaches physics", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 13. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-14", title: "Game Title 14", tagline: "One-line hook for Game 14 — replace with the real pitch.", accent: "#8BE23D", platforms: ["Mobile"], why: ["Placeholder: why this teaches negotiation", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 14. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-15", title: "Game Title 15", tagline: "One-line hook for Game 15 — replace with the real pitch.", accent: "#2FE6A6", platforms: ["PC", "Switch"], why: ["Placeholder: why this teaches architecture", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 15. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-16", title: "Game Title 16", tagline: "One-line hook for Game 16 — replace with the real pitch.", accent: "#2FD8E6", platforms: ["Mobile", "PC"], why: ["Placeholder: why this teaches probability", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 16. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-17", title: "Game Title 17", tagline: "One-line hook for Game 17 — replace with the real pitch.", accent: "#4C8CFF", platforms: ["Console", "PC"], why: ["Placeholder: why this teaches ecology", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 17. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-18", title: "Game Title 18", tagline: "One-line hook for Game 18 — replace with the real pitch.", accent: "#7C5CFF", platforms: ["Switch", "Mobile"], why: ["Placeholder: why this teaches typing / speed", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 18. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-19", title: "Game Title 19", tagline: "One-line hook for Game 19 — replace with the real pitch.", accent: "#C25CFF", platforms: ["PC"], why: ["Placeholder: why this teaches code / logic", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 19. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-20", title: "Game Title 20", tagline: "One-line hook for Game 20 — replace with the real pitch.", accent: "#FF5CAE", platforms: ["Console", "Switch", "PC"], why: ["Placeholder: why this teaches map reading", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 20. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-21", title: "Game Title 21", tagline: "One-line hook for Game 21 — replace with the real pitch.", accent: "#FF3B69", platforms: ["Mobile"], why: ["Placeholder: why this teaches budgeting", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 21. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-22", title: "Game Title 22", tagline: "One-line hook for Game 22 — replace with the real pitch.", accent: "#FF8A3D", platforms: ["PC", "Switch"], why: ["Placeholder: why this teaches communication", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 22. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-23", title: "Game Title 23", tagline: "One-line hook for Game 23 — replace with the real pitch.", accent: "#FFD23F", platforms: ["Mobile", "PC"], why: ["Placeholder: why this teaches strategy", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 23. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-24", title: "Game Title 24", tagline: "One-line hook for Game 24 — replace with the real pitch.", accent: "#8BE23D", platforms: ["Console", "PC"], why: ["Placeholder: why this teaches perseverance", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 24. Replace with a couple of sentences about what the game actually is.", link: "#" },
  { slug: "game-25", title: "Game Title 25", tagline: "One-line hook for Game 25 — replace with the real pitch.", accent: "#2FE6A6", platforms: ["Switch", "Mobile"], why: ["Placeholder: why this teaches creativity", "Placeholder: what makes it fun", "Placeholder: who it's great for"], description: "Placeholder description for Game 25. Replace with a couple of sentences about what the game actually is.", link: "#" },
];
