#!/usr/bin/env python3
"""Rebuilds assets/pc.svg from Paul's drawing at assets/source/mobo.svg.

Not part of the site and not a build step: the site ships assets/pc.svg as a
plain file. This exists only so that a re-export from Affinity does not mean
identifying every layer by hand again.

Affinity dropped the layer names on export, so the drawing arrives as fifteen
anonymous top level elements. LAYERS below maps their order to what they are.
If the drawing is re-exported with a different number of layers, or reordered,
check LAYERS against a numbered render before running this.

    python3 assets/source/rebuild-pc-svg.py     # run from tools/pcparts/
"""
import xml.dom.minidom as m

SRC, OUT = 'assets/source/mobo.svg', 'assets/pc.svg'

# order in the exported file -> what it is
LAYERS = ['psu', 'board', 'sata', 'power-connectors', 'rear-io', 'fans',
          'wifi-ethernet', 'chipset', 'pcie-slots', 'nvme', 'cpu', 'ram',
          'aio', 'gpu', 'window']

# groups written to pc.svg, in painting order. Stacking is load bearing:
# cpu before aio and pcie-slots before gpu, so a covering part really covers.
GROUPS = [
    ('mobo-bare',    ['board', 'sata', 'power-connectors', 'wifi-ethernet', 'chipset']),
    ('part-psu',     ['psu']),
    ('part-io',      ['rear-io']),
    ('part-fans',    ['fans']),
    ('part-slots',   ['pcie-slots']),
    ('part-storage', ['nvme']),
    ('part-cpu',     ['cpu']),
    ('part-ram',     ['ram']),
    ('part-cooler',  ['aio']),
    ('part-gpu',     ['gpu']),
    ('case-glass',   ['window']),
]

CASE = '''<g id="case-shell">
    <rect x="-100" y="-100" width="3744" height="3744" rx="48" fill="#0e1219"/>
    <rect x="-100" y="-100" width="3744" height="3744" rx="48" fill="none" stroke="#5b6577" stroke-width="26"/>
  </g>'''

HITS = '''<g id="hit">
    <rect id="hit-mobo"    x="700"  y="1250" width="800"  height="280"/>
    <rect id="hit-io"      x="-8"   y="194"  width="404"  height="1162"/>
    <rect id="hit-fans"    x="3141" y="0"    width="295"  height="2834"/>
    <rect id="hit-psu"     x="0"    y="2835" width="1772" height="709"/>
    <rect id="hit-slots"   x="496"  y="2340" width="1047" height="299"/>
    <rect id="hit-storage" x="515"  y="1560" width="999"  height="219"/>
    <rect id="hit-ram"     x="2102" y="105"  width="389"  height="1608"/>
    <rect id="hit-cpu"     x="1269" y="618"  width="402"  height="457"/>
    <path id="hit-cooler"  d="M1074,450 h780 v780 h-780 Z M2836,0 h295 v2835 h-295 Z"/>
    <rect id="hit-gpu"     x="1"    y="1857" width="2799" height="472"/>
    <rect id="hit-glass"   x="0"    y="0"    width="3543" height="3543"/>
  </g>'''

top = [c for c in m.parse(SRC).documentElement.childNodes if c.nodeType == 1]
assert len(top) == len(LAYERS), f'expected {len(LAYERS)} layers, found {len(top)}'
by = dict(zip(LAYERS, top))

by['gpu'].setAttribute('width', '2799.27')   # it ran across the radiator
by['window'].setAttribute('style', '')       # the stylesheet decides how glass reads

body = '\n  '.join(
    f'<g id="{gid}">' + ''.join(by[n].toxml() for n in names) + '</g>'
    for gid, names in GROUPS)

open(OUT, 'w').write(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="-140 -140 3824 3824" id="pc-diagram"
     role="img" aria-label="Cutaway view of a micro ATX desktop computer with the side panel in place"
     style="fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;">

  <!-- Generated by assets/source/rebuild-pc-svg.py. Edit the drawing, not this. -->

  {CASE}
  {body}

  {HITS}
</svg>
''')
print(f'wrote {OUT}')
